apiVersion: autoscaling.internal.knative.dev/v1alpha1
kind: PodAutoscaler
metadata:
  annotations:
    autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
    autoscaling.knative.dev/metric: concurrency
    serving.knative.dev/creator: kubernetes-admin
  creationTimestamp: "2022-10-29T08:44:18Z"
  generation: 2
  labels:
    app: hello-world-00001
    serving.knative.dev/configuration: hello-world
    serving.knative.dev/configurationGeneration: "1"
    serving.knative.dev/configurationUID: da410292-d82b-4853-9f5e-f068c9a4a736
    serving.knative.dev/revision: hello-world-00001
    serving.knative.dev/revisionUID: 3b2cd2dc-42d7-4a62-9f58-50d704353013
    serving.knative.dev/service: hello-world
    serving.knative.dev/serviceUID: 9b8d4b55-a822-48f1-a29a-5e83bd3c79ea
  name: hello-world-00001
  namespace: demo
  ownerReferences:
    - apiVersion: serving.knative.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: Revision
      name: hello-world-00001
      uid: 3b2cd2dc-42d7-4a62-9f58-50d704353013
  resourceVersion: "4172201"
  uid: 53cbed59-b863-420a-b718-1ab85394e94c
spec:
  protocolType: http1
  reachability: Reachable
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world-00001-deployment
status:
  actualScale: 1
  conditions:
    - lastTransitionTime: "2022-10-29T08:44:19Z"
      status: "True"
      type: Active
    - lastTransitionTime: "2022-10-29T08:44:19Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2022-10-29T08:44:19Z"
      status: "True"
      type: SKSReady
    - lastTransitionTime: "2022-10-29T08:44:19Z"
      status: "True"
      type: ScaleTargetInitialized
  desiredScale: 1
  metricsServiceName: hello-world-00001-private
  observedGeneration: 2
  serviceName: hello-world-00001