apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  annotations:
    serving.knative.dev/creator: kubernetes-admin
    serving.knative.dev/routes: hello-world
    serving.knative.dev/routingStateModified: "2022-10-29T08:44:17Z"
  creationTimestamp: "2022-10-29T08:44:17Z"
  generation: 1
  labels:
    serving.knative.dev/configuration: hello-world
    serving.knative.dev/configurationGeneration: "1"
    serving.knative.dev/configurationUID: da410292-d82b-4853-9f5e-f068c9a4a736
    serving.knative.dev/routingState: active
    serving.knative.dev/service: hello-world
    serving.knative.dev/serviceUID: 9b8d4b55-a822-48f1-a29a-5e83bd3c79ea
  name: hello-world-00001
  namespace: demo
  ownerReferences:
    - apiVersion: serving.knative.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: Configuration
      name: hello-world
      uid: da410292-d82b-4853-9f5e-f068c9a4a736
  resourceVersion: "4172202"
  uid: 3b2cd2dc-42d7-4a62-9f58-50d704353013
spec:
  containerConcurrency: 0
  containers:
    - env:
        - name: TARGET
          value: World
      image: gcr.io/knative-samples/helloworld-go
      name: user-container
      ports:
        - containerPort: 8080
          protocol: TCP
      readinessProbe:
        successThreshold: 1
        tcpSocket:
          port: 0
      resources: {}
  enableServiceLinks: false
  timeoutSeconds: 300
status:
  actualReplicas: 1
  conditions:
    - lastTransitionTime: "2022-10-29T08:44:19Z"
      severity: Info
      status: "True"
      type: Active
    - lastTransitionTime: "2022-10-29T08:44:19Z"
      status: "True"
      type: ContainerHealthy
    - lastTransitionTime: "2022-10-29T08:44:19Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2022-10-29T08:44:19Z"
      status: "True"
      type: ResourcesAvailable
  containerStatuses:
    - imageDigest: gcr.io/knative-samples/helloworld-go@sha256:5ea96ba4b872685ff4ddb5cd8d1a97ec18c18fae79ee8df0d29f446c5efe5f50
      name: user-container
  desiredReplicas: 1
  observedGeneration: 1