apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  annotations:
    serving.knative.dev/creator: kubernetes-admin
    serving.knative.dev/routes: helloworld-go
    serving.knative.dev/routingStateModified: "2022-11-23T12:24:24Z"
  creationTimestamp: "2022-11-23T12:24:24Z"
  generation: 1
  labels:
    serving.knative.dev/configuration: helloworld-go
    serving.knative.dev/configurationGeneration: "1"
    serving.knative.dev/configurationUID: 696be2d8-d1c8-4ca0-91eb-e049608d6662
    serving.knative.dev/routingState: active
    serving.knative.dev/service: helloworld-go
    serving.knative.dev/serviceUID: eafca205-36a7-454e-ac97-4e0a4fd783d8
  name: helloworld-go-00001
  namespace: test
  ownerReferences:
    - apiVersion: serving.knative.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: Configuration
      name: helloworld-go
      uid: 696be2d8-d1c8-4ca0-91eb-e049608d6662
  resourceVersion: "4909"
  uid: e5bc03c9-8992-481e-bd0c-effa7a8edfe9
spec:
  containerConcurrency: 0
  containers:
    - env:
        - name: TARGET
          value: Go Sample v1
      image: gcr.io/knative-samples/helloworld-go
      name: user-container
      readinessProbe:
        successThreshold: 1
        tcpSocket:
          port: 0
      resources: {}
  enableServiceLinks: false
  timeoutSeconds: 300
status:
  actualReplicas: 1
  conditions:
    - lastTransitionTime: "2022-11-23T12:24:26Z"
      severity: Info
      status: "True"
      type: Active
    - lastTransitionTime: "2022-11-23T12:24:26Z"
      status: "True"
      type: ContainerHealthy
    - lastTransitionTime: "2022-11-23T12:24:26Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2022-11-23T12:24:26Z"
      status: "True"
      type: ResourcesAvailable
  containerStatuses:
    - imageDigest: gcr.io/knative-samples/helloworld-go@sha256:5ea96ba4b872685ff4ddb5cd8d1a97ec18c18fae79ee8df0d29f446c5efe5f50
      name: user-container
  desiredReplicas: 1
  observedGeneration: 1
---